import type { GameStateData } from "./types";

// Distinct crew accent colours (GDD §5.4)
const ACCENT = {
  amber: "#d9a441",
  green: "#9bb04a",
  violet: "#a081c9",
  cyan: "#5fb6c0",
  orange: "#d07a3c",
  plum: "#b06aa0",
  blue: "#4f8fc0",
  steel: "#9a8f7a",
};

export const initialState: GameStateData = {
  day: 42,
  clock: "18:47",
  vitals: { oxygen: 64, power: 71, hull: 78 },
  resources: { food: 164, water: 236, salvage: 782, med: 38 },

  crew: [
    {
      id: "mara",
      name: "Mara Kovalenko",
      role: "Hydroponics Specialist",
      accent: ACCENT.amber,
      traits: ["Diligent", "Compassionate", "Stubborn"],
      background:
        "Before the Collapse, a botanist and researcher in agricultural systems. Has kept the crops alive through countless crises.",
      portrait: "/assets/crew/character1.png",
      history: [
        { with: "Dr. Elias Vance", text: "We argued for a week about nutrient ratios. He was right. I still won't admit it." },
        { with: "Samir Okonkwo", text: "He swears my tomatoes taste of rust. He's not wrong — but he keeps asking for more." },
      ],
      state: { energy: 72, hunger: 48, health: 88, morale: 64 },
    },
    {
      id: "griff",
      name: "Griff Mercer",
      role: "Mechanic",
      accent: ACCENT.green,
      traits: ["Steady", "Lone Wolf"],
      background:
        "A born repairman with a handmade prosthetic arm. Trusts machines more than people.",
      portrait: "/assets/crew/character2.png",
      history: [
        { with: "Bjorn Hale", text: "Bjorn forged me a new wrench when mine snapped in the reactor. Didn't say a word — just left it on my bunk." },
      ],
      state: { energy: 81, hunger: 33, health: 76, morale: 70 },
    },
    {
      id: "mira",
      name: "Mira Koval",
      role: "Guard / Officer",
      accent: ACCENT.violet,
      traits: ["Leader", "Coward"],
      background:
        "Ex-bounty hunter in salvaged riot gear. Keeps order aboard — steel nerves, a soft spot for the young.",
      portrait: "/assets/crew/character3.png",
      state: { energy: 58, hunger: 61, health: 69, morale: 52 },
    },
    {
      id: "elias",
      name: "Dr. Elias Vance",
      role: "Researcher",
      accent: ACCENT.cyan,
      traits: ["Observant", "Insomniac"],
      background:
        "A systems researcher obsessed with the O₂ and hydroponics rigs. Sleeps little, theorizes much.",
      portrait: "/assets/crew/character4.png",
      history: [
        { with: "Mara Kovalenko", text: "Mara keeps the gardens alive on instinct. I keep telling her it's chemistry. She just smiles." },
      ],
      state: { energy: 49, hunger: 44, health: 82, morale: 60 },
    },
    {
      id: "samir",
      name: "Samir Okonkwo",
      role: "Cook",
      accent: ACCENT.plum,
      traits: ["Optimist"],
      background:
        "Runs the galley with a grin. A good meal, he says, is the only morale that lasts.",
      portrait: "/assets/crew/character5.png",
      history: [
        { with: "Mira Koval", text: "Mira never smiles at the table — until the day I made stew from the last real onion. Almost." },
      ],
      state: { energy: 77, hunger: 30, health: 90, morale: 78 },
    },
    {
      id: "bjorn",
      name: "Bjorn Hale",
      role: "Blacksmith",
      accent: ACCENT.orange,
      traits: ["Steady", "Resilient"],
      background: "Forge and heavy repair. If it's bent, he'll beat it straight.",
      portrait: "/assets/crew/character6.png",
      state: { energy: 66, hunger: 52, health: 71, morale: 58 },
    },
    {
      id: "tomas",
      name: "Tomas Reyes",
      role: "Fisher",
      accent: ACCENT.blue,
      traits: ["Resilient"],
      background: "Worked the drowned coasts before MARA. Reads the water like a book.",
      portrait: "/assets/crew/character7.png",
      state: { energy: 64, hunger: 40, health: 80, morale: 66 },
      exploringReturnsIn: 4 * 3600 + 12 * 60 + 30,
    },
    {
      id: "cole",
      name: "Cole Renner",
      role: "Scavenger",
      accent: ACCENT.steel,
      traits: ["Resilient", "Insomniac"],
      background: "Survives where others can't. Brings back salvage and rumors.",
      portrait: "/assets/crew/character8.png",
      state: { energy: 70, hunger: 55, health: 62, morale: 48 },
      // single expedition party — same return time as the others exploring
      exploringReturnsIn: 4 * 3600 + 12 * 60 + 30,
    },
  ],
  emptyCrewSlots: 1,

  rooms: [
    {
      id: "reactor",
      name: "Power · Reactor",
      short: "REACTOR",
      accent: "#c2502f",
      level: 1,
      produces: "Power",
      consumes: "—",
      sceneBase: "/assets/rooms/generator",
      sceneLevels: 3,
      workSlots: [],
      upgradeSlots: [null],
      lockedWork: 0,
      lockedUpgrade: 2,
      developed: true,
      cycle: 30,
    },
    {
      id: "o2",
      name: "O₂ Generation",
      short: "O₂",
      accent: "#5fb6c0",
      level: 1,
      variant: "Algae",
      produces: "O₂",
      consumes: "Water + light",
      sceneBase: "/assets/rooms/algae",
      sceneLevels: 3,
      workSlots: [],
      upgradeSlots: [null],
      lockedWork: 0,
      lockedUpgrade: 1,
      developed: true,
      cycle: 55,
    },
    {
      id: "food",
      name: "Food Production",
      short: "FOOD",
      accent: "#9bb04a",
      level: 1,
      variant: "Garden · Hydroponics",
      produces: "Food",
      consumes: "Water + light",
      sceneBase: "/assets/rooms/hydroponics",
      sceneLevels: 3,
      workSlots: ["mara", null, null],
      upgradeSlots: [null],
      lockedWork: 0,
      lockedUpgrade: 1,
      developed: true,
      cycle: 72,
    },
    {
      id: "fishery",
      name: "Food · Fishery",
      short: "FISHERY",
      accent: "#4f8fc0",
      level: 1,
      variant: "Piscifactoría",
      produces: "Food",
      consumes: "Power + Salvage",
      sceneBase: "/assets/rooms/pisifactory",
      sceneLevels: 2,
      specGateLevel: 2,
      specChoices: [
        {
          key: "selectiva",
          label: "Selective Fishing",
          desc: "Sustainable, steady yield, fewer events.",
          cost: "Salvage 120 · 1 crew",
          sceneBase: "/assets/rooms/fishing",
          sceneLevels: 2,
        },
        {
          key: "arrastre",
          label: "Trawling",
          desc: "Big hauls, +exterior risk, depletes the grounds.",
          cost: "Salvage 140 · 1 crew",
          sceneBase: "/assets/rooms/trawling",
          sceneLevels: 2,
        },
      ],
      workSlots: [null, null],
      upgradeSlots: [null],
      lockedWork: 0,
      lockedUpgrade: 1,
      developed: true,
      cycle: 20,
    },
    {
      id: "water",
      name: "Water Generation",
      short: "DESALINATOR",
      accent: "#4f8fc0",
      level: 1,
      variant: "Desalinator",
      produces: "Water",
      consumes: "Power",
      sceneBase: "/assets/rooms/desalination",
      sceneLevels: 3,
      workSlots: ["mira"],
      upgradeSlots: [null],
      lockedWork: 1,
      lockedUpgrade: 1,
      developed: true,
      cycle: 41,
    },
    {
      id: "habitat",
      name: "Habitat",
      short: "HABITAT",
      accent: "#caa84b",
      level: 1,
      produces: "Rest / Meals",
      consumes: "Food (when eating)",
      sceneBase: "/assets/rooms/habitat",
      sceneLevels: 1,
      workSlots: [null, null],
      upgradeSlots: [null],
      lockedWork: 1,
      lockedUpgrade: 1,
      developed: true,
      cycle: 0,
    },
    {
      id: "workshop",
      name: "Workshop-Airlock",
      short: "WORKSHOP",
      accent: "#d07a3c",
      level: 1,
      produces: "Repair / Expedition",
      consumes: "Salvage",
      sceneBase: "/assets/rooms/workshop",
      sceneLevels: 3,
      workSlots: ["griff"],
      upgradeSlots: [null, null],
      lockedWork: 1,
      lockedUpgrade: 1,
      developed: true,
      cycle: 0,
    },
    {
      id: "infirmary",
      name: "Infirmary-Lab",
      short: "INFIRMARY-LAB",
      accent: "#b06aa0",
      level: 1,
      variant: "Biological",
      produces: "Healing / Research",
      consumes: "Med",
      sceneBase: "/assets/rooms/infirmary",
      sceneLevels: 1,
      workSlots: [null, null],
      upgradeSlots: [],
      lockedWork: 0,
      lockedUpgrade: 2,
      developed: false,
      cycle: 0,
    },
  ],

  events: [
    {
      id: "fire",
      family: "A",
      title: "FIRE — Machine Room",
      description:
        "A short circuit set the machine room ablaze. The hull takes damage each tick and the fire will spread if left unchecked.",
      severity: "high",
      body: "posts",
      responseWindow: 95,
      posts: [
        { label: "Water pumps", mitigates: "Speeds extinguishing", crewId: null },
        { label: "On the fire", mitigates: "Puts out the blaze (Health risk)", crewId: null },
        { label: "Tend the wounded", mitigates: "Prevents deaths", crewId: null },
      ],
    },
    {
      id: "lowfood",
      family: "A",
      title: "LOW FOOD SUPPLY",
      description: "Rations have fallen below the safe threshold.",
      severity: "med",
      body: "posts",
      responseWindow: 240,
      posts: [{ label: "Reassign to farming", mitigates: "Boosts output", crewId: null }],
    },
    {
      id: "build-o2",
      family: "D",
      title: "«The air is going stale»",
      description:
        "Mara: «The O₂ generator can barely breathe. If we don't get it running soon, the station's air won't hold.» — Build / reactivate a room.",
      severity: "med",
      body: "cards",
      responseWindow: 600,
      cards: [
        {
          title: "Algae",
          desc: "Algae bioreactor. Consumes Water + light. Steady output.",
          cost: "Salvage 120 · 1 tech",
        },
        {
          title: "Electrolysis",
          desc: "Splits water with electricity. Consumes heavy Power + Water.",
          cost: "Salvage 150 · 1 tech",
        },
      ],
    },
  ],

  log: [
    { time: "18:32", text: "Hypoxia resolved in the Habitat." },
    { time: "18:11", text: "Crew returned from expedition (Workshop-Airlock)." },
    { time: "17:48", text: "Discovered: rusted valve." },
    { time: "17:22", text: "Hull breach in Sector C-3." },
    { time: "16:59", text: "Workshop upgrade research complete." },
  ],

  selection: { kind: "room", id: "food" },
  pendingSlot: null,
};
